### ISSUE TITLE
const_extenders.txt is missing instructions

### ISSUE THREAD

**Issue by Rot127** [radareorg/r2hexagon#4]
The const_extenders.txt file is missing some instructions which therefor get not extended through immext(#u26).
This leads occasionally to disassembly like that:
![ss-struct](https://user-images.githubusercontent.com/45763064/63541671-1e4baa00-c50e-11e9-8437-c0300d1d015d.png)
Which is not correct because the immext() instruction is always applied to the following instruction (see: Chapter 10.9 - Constant extenders Reference Manual V62)

The const_extenders.txt looks generated. @XVilka Is this is the case?
If so, can you push it please?

**Comment by XVilka** [comment]
No, they are not autogenerated, since I wasn't able to find a way to distinguish them from the manual text. There is some table of instructions that can be extended, but I found it has some discrepancies with the rest of manual. So if you find something that is missing - feel free to add there.

**Comment by XVilka** [comment]
@Rot127 thanks a lot! I merged your PRs, can you please send a PR to the radare2 main repo, so your authorship of these changes will be clear from the git history. Same for the calling convention.
