### ISSUE TITLE
Inconsistent C-files when executing import.py multiple times

### ISSUE THREAD

**Issue by Rot127** [radareorg/r2hexagon#6]
There seems to be a weird bug in the script. At least on my machine the generated hexagon_disas.c stays  not consistent over multiple executions of the script:

```
$> git clone https://github.com/radareorg/r2hexagon && cd r2hexagon
$> ./import.py > /dev/null
$> git diff --numstat r2/hexagon_disas.c
$> 
$> ./import.py > /dev/null
$> git diff --numstat r2/hexagon_disas.c
8       9       r2/hexagon_disas.c
$>
$> ./import.py > /dev/null
$> git diff --numstat r2/hexagon_disas.c
32      33      r2/hexagon_disas.c
```
Try it again.
```
$> git clone https://github.com/radareorg/r2hexagon && cd r2hexagon
$> ./import.py > /dev/null
$> git diff --numstat r2/hexagon_disas.c
10      10      r2/hexagon_disas.c

$> ./import.py > /dev/null
$> git diff --numstat r2/hexagon_disas.c
33      33      r2/hexagon_disas.c
```

**Comment by XVilka** [comment]
@Rot127 what Python version do you use? Because older Python version had non-deterministic dictionary order. See https://stackoverflow.com/questions/14956313/why-is-dictionary-ordering-non-deterministic for more information. I use Python 3.7.4 on my machine and have no such problem.

**Comment by Rot127** [comment]
That solved it. Thanks. Wasn't expecting something like that.
